### ISSUE TITLE
Site crashes when attempting to ban a user without inputting username

### ISSUE THREAD

**Issue by powsune** [tovyblox/tovy#71]
Logs below:

`uncaughtException Error: User not found
at /app/node_modules/noblox.js/lib/user/getIdFromUsername.js:33:15
at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
at processImmediate (node:internal/timers:466:21)
Exiting...`

**Comment by Ovadux** [comment]
A fix for this issue was proposed in #66. Promise rejection when getting user id from username was unhandled, causing invalid or non-existing usernames to throw a fatal error.

**Comment by Ovadux** [comment]
This issue has been patched in the [latest update](https://github.com/tovyblox/tovy/commit/8aadd02799b4d278a1ad2f9c387322b882423050).
